### ISSUE TITLE
Connects but then shows "sendto failed: EPIPE (broken pipe): <ip address>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pot8oe/mythmote#83]
```
What steps will reproduce the problem?
1.Install mythmote and it connects
2.Press a button and it does nothing 
3.Press a second button and you get "Sendto failed: EPIPE (broken pipe): ip 
address

What is the expected output? What do you see instead?
That is works, first press does nothing, second press brings up this message

What version of the product are you using? On what operating system?
Mythmote 1.8.5, Mythbuntu 12.04 

Please provide any additional information below.
I get the same result on any phone or tablet I use mythmote on, so I think it 
is my mythbuntu settings that need tweaking. I have set up all the remote 
settings I can find and I think they are o.k. (hence why it connects and then 
fails). Could it be my router (it's a Sky router).
```

Original issue reported on code.google.com by `SarahMcL...@googlemail.com` on 23 Dec 2013 at 8:52

**Comment by pot8oe** [comment]
Following is a reported resolution:
> 
> Hi Thomas,
> 
> I worked out what my problem was and I wanted to share it with you.
> 
> My issue was a subnet issue as I have my media network separated into a different vLAN and was getting this error in my Frontend log:
> 2018-06-19T13:23:03.715350+10:00 mythfrontend[1672]: W CoreContext mythcorecontext.cpp:1313 (CheckSubnet) MythCoreContext::CheckSubnet(): Denied connection from ip address: 192.168.254.153
> 2018-06-19T13:23:45.543517+10:00 mythfrontend[1672]: W CoreContext mythcorecontext.cpp:1275 (CheckSubnet) MythCoreContext::CheckSubnet(): Repeat denied connection from ip address: 192.168.254.153
> 
> When I researched this issue I found that by default MythTV does not allow connections from different subnets. To fix this I had to change a setting in MythTV-Setup:
> 1. General -> Host Address Backend Setup -> Allow Connections from All Subnets
> 
> When I turned this on it works for me now. Obviously I am aware of the security implications of allowing this feature.

Leaving this here to hopefully help anyone else out that uses mythmote & mythtv across different subnets.

**Comment by ahofecker** [comment]
Had the same issue as pot8oe, only the changing the setting on the back end had no effect.

I have a separate front end and that setting does not show in the menu.

Connected to DB on back end, settings table, found the AllowConnFromAll value set to 1 for the back end, no record for the front end.  I added the record and BingPot!

**Comment by troyloftus** [comment]
This solution (adding AllowConnFrontAll to the database for a separate mythfrontend) was still required and worked as of late 2023 on MythTV v33.1
