### ISSUE TITLE
Misuse of AsyncTask

### ISSUE THREAD

**Issue by cuixiaoyiyi** [pot8oe/mythmote#93]
According to our research, there are misuses about the following AsyncTask class:
( tkj.android.homecontrol.mythmote. GestureBuilderActivity)
```
 private GesturesLoadTask mTask;
     //....
private class GesturesLoadTask extends AsyncTask<Void, NamedGesture, Integer>
```
The problems are:

1. it is inner class. It holds strong reference to the GUI element of Activity( GestureBuilderActivity ), which can lead to memory leak when the Activity is destroyed and the AsyncTask did not finish
2. Its instance is cancelled before the Activity is destroyed. But in the doInBackground method there are for or while loops without the call of isCancelled() . These loops may not be able to terminate when the task is cancelled. This will cause waste of resources or even flashback

I think we can make following changes to fix the misuse problems:
1. I think the GUI-related fields should be wrapped into WeakReference. Take 
`private final GestureBuilderActivity _context` as example, it can be changed to `private final WeakReference<GestureBuilderActivity> _context`.
2. Every loop should check the status of AsyncTask to break the loop.
```
while(condition1){
     if(isCancelled()){
          break;
     }
     //blablabla…
     while(condition2){
         if(isCancelled()){
              break;
         }
         //blablabla…
     }
}
```

These are my suggestions above, thank you.

**Comment by pot8oe** [comment]
1. The AsyncTask does not hold a direct reference to the activity and the AsyncTask reference in the activity is cleared in onDestroy(). I expect the Activity to be garbage collected correctly once onDestroy() has been called by the Android system.

2. I've addressed the missing call to isCancelled() in the inner for loop.

Note: GestureBuilderActivity is not in use as the preference was commented out years ago.
