### ISSUE TITLE
toggle bookmark button

### ISSUE THREAD

**Issue by msillence** [pot8oe/mythmote#94]
It seems that mythtv has removed the enter/space to toggle bookmarks
The keyboard mapping to reapply this works for the keyboard but not for the control port

Please could you add a dedicated button for bookmark toggling?

**Comment by pot8oe** [comment]
Hi,

Would changing the key binding of a button you do not use be adequate?

1. Preference -> Button Long-Press action -> Edit Key-binding. 
2. Long-press the button you will change.
3. Change command sent to mythfrontend.
4. Restore long-press action to Auto Repeat (Optional)

Reference: https://www.mythtv.org/wiki/Frontend_control_socket for possible commands. I'm not sure the key-combo for bookmarking and I don't have a functional MythTV setup at present to help test.

**Comment by msillence** [comment]
Yes, that worked thanks
